# Generated by Django 4.1.1 on 2023-10-20 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_proyecto_date_proyecto_imajeproj'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyecto',
            old_name='imajeproj',
            new_name='imageproj',
        ),
    ]
