# Generated by Django 4.2.7 on 2023-11-16 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_rename_imajeproj_proyecto_imageproj'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='contenido',
            field=models.TextField(default='Este proyecto fue realizado con el propósito de [propósito del proyecto], llevado a cabo por [nombre del responsable] y su equipo el [fecha de realización], con el objetivo de [objetivo del proyecto].'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fecha',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='imagen_detalle',
            field=models.FileField(null=True, upload_to='detalles_proyectos/'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='motivo',
            field=models.CharField(default='a', max_length=200),
            preserve_default=False,
        ),
    ]
