# Generated by Django 4.2.7 on 2023-11-16 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0004_proyecto_contenido_proyecto_fecha_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='contenido',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='imagen_detalle',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='motivo',
        ),
    ]
