# Generated by Django 4.1.1 on 2023-10-27 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ubicaciones', '0002_lugares_delete_proyecto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lugares',
            options={'ordering': ['name'], 'verbose_name': 'Ubicacion', 'verbose_name_plural': 'Ubicaciones'},
        ),
    ]
